package com.winston.entity;

import cn.afterturn.easypoi.excel.annotation.Excel;
import cn.afterturn.easypoi.excel.annotation.ExcelTarget;

import javax.validation.constraints.NotBlank;
import java.io.Serializable;

@ExcelTarget("20")
public class ExcelEnTity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_entity.id
     *
     * @mbg.generated
     */
    @Excel(name = "id", width = 15)
    @NotBlank(message = "该字段不能为空")
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_entity.name
     *
     * @mbg.generated
     */
    @Excel(name = "姓名", orderNum = "0", width = 30)
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_entity.sex
     *
     * @mbg.generated
     */
    @Excel(name = "性别", replace = {"男_1", "女_2"},orderNum = "1", width = 30)
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_entity.birthday
     *
     * @mbg.generated
     */
    @Excel(name = "生日", exportFormat = "yyyy-MM-dd", orderNum = "2", width = 30)
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table excel_entity
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_entity.id
     *
     * @return the value of excel_entity.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_entity.id
     *
     * @param id the value for excel_entity.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_entity.name
     *
     * @return the value of excel_entity.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_entity.name
     *
     * @param name the value for excel_entity.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_entity.sex
     *
     * @return the value of excel_entity.sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_entity.sex
     *
     * @param sex the value for excel_entity.sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_entity.birthday
     *
     * @return the value of excel_entity.birthday
     *
     * @mbg.generated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_entity.birthday
     *
     * @param birthday the value for excel_entity.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }
}