package com.winston.mapper;

import com.winston.entity.ExcelEnTity;
import com.winston.entity.ExcelEnTityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExcelEnTityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel_entity
     *
     * @mbg.generated
     */
    long countByExample(ExcelEnTityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel_entity
     *
     * @mbg.generated
     */
    int deleteByExample(ExcelEnTityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel_entity
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel_entity
     *
     * @mbg.generated
     */
    int insert(ExcelEnTity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel_entity
     *
     * @mbg.generated
     */
    int insertSelective(ExcelEnTity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel_entity
     *
     * @mbg.generated
     */
    List<ExcelEnTity> selectByExample(ExcelEnTityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel_entity
     *
     * @mbg.generated
     */
    ExcelEnTity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel_entity
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ExcelEnTity record, @Param("example") ExcelEnTityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel_entity
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ExcelEnTity record, @Param("example") ExcelEnTityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel_entity
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ExcelEnTity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel_entity
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ExcelEnTity record);
}